name: smartup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.1.0
  url_launcher: ^6.1.10
  sqflite: ^2.3.0   # latest stable
  path: ^1.8.3      # for file paths
  path_provider: ^2.1.1 # to locate database path`

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/gardener.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
  - assets/icon/gardener.png
  - assets/categories.json
  - assets/jobs.json

  
